services:
  - type: web
    name: cpa-api
    env: node
    rootDir: apps/api
    buildCommand: |
      cd ../..            # 🔥 muhim — rootga chiqib oladi
      corepack enable
      pnpm install
      pnpm --filter apps-api build
    startCommand: pnpm --filter apps-api start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 4000

  - type: web
    name: cpa-web
    env: node
    rootDir: apps/web
    buildCommand: |
      cd ../..            # 🔥 rootga chiqib oladi
      corepack enable
      pnpm install
      pnpm --filter apps-web build
    startCommand: pnpm --filter apps-web start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://cpa-api.onrender.com
      - key: PORT
        value: 3000
